repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      # force black to run on whole repo & keep settings from pyproject.toml
      pass_filenames: false
      args: [.]
