environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      DISPLAY: :99.0
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS

matrix:
  fast_finish: true

init:
  - appveyor version

# job-specific configurations
for:
  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

    before_build:
    - cmd: sudo apt install libxkbcommon-x11-0
        /sbin/start-stop-daemon --start --quiet \
        --pidfile /tmp/custom_xvfb_99.pid --make-pidfile \
        --background --exec /usr/bin/Xvfb \
        -- :99 -screen 0 1920x1200x24 -ac +extension GLX

build_script:
  - cmd: python -m pip install briefcase tomlkit wheel
  - cmd: python -m pip install -e .[pyside2]
  - cmd: VER=`python bundle.py --version`
  - cmd: echo "::set-env name=version::$VER"
  - cmd: python -m bundle
