name: napari
base: core18 # the base snap is the execution environment for this snap
version: '0.1.test' # just for humans, typically '1.2+git' or '1.3.2'
summary: a fast, interactive, multi-dimensional image viewer for python
description: |
  napari is a fast, interactive, multi-dimensional image viewer for Python.
  It's designed for browsing, annotating, and analyzing large multi-dimensional
  images. It's built on top of Qt, vispy, and the scientific Python stack.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  napari:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - libfreetype6
      - libpng16-16
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libavahi-client3
      - libavahi-common3
      - libcairo-gobject2
      - libcairo2
      - libcups2
      - libdatrie1
      - libdrm2
      - libegl1
      - libepoxy0
      - libfontconfig1
      - libgdk-pixbuf2.0-0
      - libgl1
      - libglvnd0
      - libglx0
      - libgraphite2-3
      - libgtk-3-0
      - libharfbuzz0b
      - libicu60
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libthai0
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwayland-server0
      - libx11-6
      - libx11-xcb1
      - libxau6
      - libxcb-glx0
      - libxcb-render0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-xfixes0
      - libxcb-xkb1
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon-x11-0
      - libxkbcommon0
      - libxrandr2
      - libxrender1
      - libxtst6
    requirements: [requirements/default.txt]

apps:
  napari:
    command: bin/napari
    plugs: [home, desktop, opengl, x11, wayland]