"""This is a script to generate a pixi.toml file to test napari against packages released on conda-forge

This script is reading pyproject.toml and generates a pixi.toml file

Each dependency group and extras should be mapped to a separate feature.

The generated pixi.toml will include pytest tasks similar to those in tox.ini:
- py{310,311,312,313,314}-{linux,macos,windows}-{pyqt5,pyqt6,pyside6,headless,pyqt6_no_numba,pyqt5_no_numba}-{cov,no_cov}
"""

from pathlib import Path

try:
    import tomllib
except ImportError:
    import tomli as tomllib


def load_pyproject():
    """Load pyproject.toml content."""
    pyproject_path = Path(__file__).parent.parent / 'pyproject.toml'
    with open(pyproject_path, 'rb') as f:
        return tomllib.load(f)


def parse_dependency_spec(dep_spec):
    """Parse a dependency specification to extract package name and version constraint.

    Args:
        dep_spec: A dependency string like "numpy>=1.24.2" or "pytest-qt >=4.4.0; python_version > '3.10'"

    Returns:
        tuple: (package_name, version_constraint)
    """
    # Remove environment markers like ; python_version > '3.10'
    dep_spec = dep_spec.split(';')[0].strip()

    # Extract package name and version
    for sep in ['>=', '<=', '==', '!=', '>', '<', '~=']:
        if sep in dep_spec:
            parts = dep_spec.split(sep, 1)
            # Remove extras like [html_clean] from package name
            pkg_name = parts[0].split('[')[0].strip()
            version = parts[1].strip()
            # Convert to conda-style version constraint
            if sep == '>=':
                return (pkg_name, f'>={version}')
            if sep == '<=':
                return (pkg_name, f'<={version}')
            if sep == '==':
                return (pkg_name, f'=={version}')
            if sep == '~=':
                return (pkg_name, f'~={version}')
            if sep == '>':
                return (pkg_name, f'>{version}')
            if sep == '<':
                return (pkg_name, f'<{version}')

    # No version constraint found, just extract package name without extras
    pkg_name = dep_spec.split('[')[0].strip()
    return (pkg_name, '*')


def pypi_to_conda_name(pkg_name):
    """Convert PyPI package name to conda-forge package name.

    Args:
        pkg_name: PyPI package name

    Returns:
        conda-forge package name
    """
    # Map PyPI package names to conda package names where they differ
    pypi_to_conda_map = {
        'PyYAML': 'pyyaml',
        'Pillow': 'pillow',
        'PyOpenGL': 'pyopengl',
        'PyQt5': 'pyqt',
        'docstring-parser': 'docstring_parser',
        'docstring_parser': 'docstring_parser',
    }

    # Check if there's a specific mapping
    if pkg_name in pypi_to_conda_map:
        return pypi_to_conda_map[pkg_name]

    # Default: lowercase and replace underscores with hyphens
    return pkg_name.lower().replace('_', '-')


def generate_pixi_toml(pyproject_data):
    """Generate pixi.toml content from pyproject.toml."""

    # Extract project info
    project = pyproject_data['project']
    project_name = project['name']
    dependencies = project['dependencies']
    optional_deps = project.get('optional-dependencies', {})
    dependency_groups = pyproject_data.get('dependency-groups', {})

    # Start building the pixi.toml content
    lines = []
    lines.append(f'# Generated by {Path(__file__).name}')
    lines.append(f'# Project: {project_name}\n')
    lines.append('[workspace]')
    lines.append(f'name = "{project_name}"')
    lines.append('channels = ["conda-forge"]')
    lines.append('platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]\n')

    # Main dependencies from pyproject.toml
    lines.append('[dependencies]')
    lines.append(f'python = "{project["requires-python"]}"')

    for dep in dependencies:
        # Skip platform-specific dependencies
        if 'platform_system' in dep:
            continue

        pkg_name, version = parse_dependency_spec(dep)
        # Convert package name to conda-forge naming
        conda_pkg_name = pypi_to_conda_name(pkg_name)
        lines.append(f'{conda_pkg_name} = "{version}"')

    # Add test-specific dependencies that aren't in pyproject.toml
    lines.append('pytest-json-report = "*"')
    lines.append('objgraph = "*"')
    lines.append('lxml-html-clean = "*"')
    lines.append('')

    # PyPI dependencies - napari itself needs to be installed from source
    lines.append('[pypi-dependencies]')
    lines.append(f'{project_name} = {{ path = ".", editable = true }}')
    lines.append('')

    # Create features for Qt backends
    lines.append('[feature.pyqt5.dependencies]')
    # Extract PyQt5 version from optional-dependencies
    pyqt5_deps = optional_deps.get('pyqt5', [])
    found_pyqt5 = False
    for dep in pyqt5_deps:
        if dep.startswith('PyQt5'):
            pkg_name, version = parse_dependency_spec(dep)
            lines.append(f'pyqt = "{version}"')
            found_pyqt5 = True
            break
    if not found_pyqt5:
        lines.append('pyqt = "*"')
    lines.append('')

    lines.append('[feature.pyqt6.dependencies]')
    pyqt6_deps = optional_deps.get('pyqt6', [])
    found_pyqt6 = False
    for dep in pyqt6_deps:
        if dep.startswith('PyQt6'):
            pkg_name, version = parse_dependency_spec(dep)
            lines.append(f'pyqt6 = "{version}"')
            found_pyqt6 = True
            break
    if not found_pyqt6:
        lines.append('pyqt6 = "*"')
    lines.append('')

    lines.append('[feature.pyside6.dependencies]')
    pyside6_deps = optional_deps.get('pyside6', [])
    found_pyside6 = False
    for dep in pyside6_deps:
        if dep.startswith('PySide6'):
            pkg_name, version = parse_dependency_spec(dep)
            lines.append(f'pyside6 = "{version}"')
            found_pyside6 = True
            break
    if not found_pyside6:
        lines.append('pyside6 = "*"')
    lines.append('')

    # Feature for numba optional dependency
    lines.append('[feature.optional-numba.dependencies]')
    numba_deps = optional_deps.get('optional-numba', [])
    if numba_deps:
        for dep in numba_deps:
            if 'numba' in dep.lower() and ';' not in dep:
                # Extract the most general constraint (without platform conditionals)
                pkg_name, version = parse_dependency_spec(dep)
                lines.append(f'numba = "{version}"')
                break
        else:
            lines.append('numba = ">=0.57.1"')
    else:
        lines.append('numba = ">=0.57.1"')
    lines.append('')

    # Feature for testing dependencies
    # Some packages are not available on conda-forge for all platforms, so we install them via PyPI
    # Also, napari-* packages should be installed from PyPI to avoid version conflicts with editable napari install
    pypi_only_packages = {
        'pyautogui',
        'tensorstore',
        'napari-metadata',
        'napari-plugin-manager',
    }

    lines.append('[feature.testing.dependencies]')
    testing_deps = dependency_groups.get('testing', [])
    seen_packages = set()
    pypi_deps = []

    # First add dependencies from optional-base (required by testing)
    optional_base_deps = optional_deps.get('optional-base', [])
    for dep in optional_base_deps:
        if isinstance(dep, str):
            # Skip only napari itself, but include napari-* packages
            pkg_name, version = parse_dependency_spec(dep)
            if pkg_name == 'napari':
                continue
            if pkg_name not in seen_packages:
                if pkg_name in pypi_only_packages:
                    pypi_deps.append(dep)
                else:
                    conda_pkg_name = pypi_to_conda_name(pkg_name)
                    lines.append(f'{conda_pkg_name} = "{version}"')
                seen_packages.add(pkg_name)

    # Add bermuda dependencies (also required by testing)
    bermuda_deps = optional_deps.get('bermuda', [])
    for dep in bermuda_deps:
        if isinstance(dep, str):
            pkg_name, version = parse_dependency_spec(dep)
            if pkg_name not in seen_packages:
                if pkg_name in pypi_only_packages:
                    pypi_deps.append(dep)
                else:
                    conda_pkg_name = pypi_to_conda_name(pkg_name)
                    lines.append(f'{conda_pkg_name} = "{version}"')
                seen_packages.add(pkg_name)

    # Then add testing-specific dependencies
    for dep in testing_deps:
        if isinstance(dep, str) and not dep.startswith('napari['):
            pkg_name, version = parse_dependency_spec(dep)
            if pkg_name not in seen_packages:
                if pkg_name in pypi_only_packages:
                    pypi_deps.append(dep)
                else:
                    conda_pkg_name = pypi_to_conda_name(pkg_name)
                    lines.append(f'{conda_pkg_name} = "{version}"')
                seen_packages.add(pkg_name)
    lines.append('')

    # Add PyPI-only dependencies for testing
    if pypi_deps:
        lines.append('[feature.testing.pypi-dependencies]')
        for dep in pypi_deps:
            pkg_name, version = parse_dependency_spec(dep)
            # Keep original PyPI package name and version spec
            lines.append(f'{pkg_name} = "{version}"')
        lines.append('')

    # Create pytest tasks for each combination
    lines.append('# Pytest tasks matching tox environments')

    # Note: Python 3.14 is excluded as it's not fully available on conda-forge yet
    python_versions = ['310', '311', '312', '313']
    backends = [
        'pyqt5',
        'pyqt6',
        'pyside6',
        'headless',
        'pyqt6-no-numba',
        'pyqt5-no-numba',
    ]

    for py_ver in python_versions:
        for backend in backends:
            env_name = f'py{py_ver}-{backend}'

            # Determine features needed
            features = ['testing']
            if backend == 'pyqt5':
                features.append('pyqt5')
                features.append('optional-numba')
            elif backend == 'pyqt6':
                features.append('pyqt6')
                features.append('optional-numba')
            elif backend == 'pyside6':
                features.append('pyside6')
                features.append('optional-numba')
            elif backend == 'pyqt5-no-numba':
                features.append('pyqt5')
            elif backend == 'pyqt6-no-numba':
                features.append('pyqt6')
            elif backend == 'headless':
                features.append('optional-numba')

            # Build pytest command
            pytest_cmd = 'python -m pytest'

            pytest_cmd += ' --color=yes --maxfail=5 --json-report --import-mode=importlib'

            # if platform == "linux":
            #     pytest_cmd += ' --pystack-threshold=60 --pystack-args="--native-all"'

            if backend == 'headless':
                pytest_cmd += ' --ignore src/napari/_vispy --ignore src/napari/_qt --ignore src/napari/_tests --ignore tools --ignore src/napari_builtins/_qt'
            else:
                pytest_cmd += ' --ignore tools'

            pytest_cmd += f' --json-report-file=report-{env_name}.json'
            pytest_cmd += ' --save-leaked-object-graph'

            lines.append(f'[feature.{env_name}.tasks]')
            lines.append(f'test = "{pytest_cmd}"')
            lines.append('')

    # Add environments section with Python version constraints
    lines.append('# Environment definitions')
    for py_ver in python_versions:
        for backend in backends:
            env_name = f'py{py_ver}-{backend}'
            features = ['testing']
            if backend in ['pyqt5', 'pyqt5-no-numba']:
                features.append('pyqt5')
            elif backend in ['pyqt6', 'pyqt6-no-numba']:
                features.append('pyqt6')
            elif backend == 'pyside6':
                features.append('pyside6')

            if backend not in ['pyqt5-no-numba', 'pyqt6-no-numba', 'headless']:
                features.append('optional-numba')

            features.append(env_name)

            py_version_formatted = f'{py_ver[0]}.{py_ver[1:]}'
            lines.append(f'[environments.{env_name}]')
            features_str = ', '.join(f'"{f}"' for f in features)
            lines.append(f'features = [{features_str}]')
            lines.append('')

    # Add Python version dependencies to each feature
    lines.append('# Python version constraints for each environment feature')
    for py_ver in python_versions:
        for backend in backends:
            env_name = f'py{py_ver}-{backend}'
            py_version_formatted = f'{py_ver[0]}.{py_ver[1:]}'
            lines.append(f'[feature.{env_name}.dependencies]')
            lines.append(f'python = "{py_version_formatted}.*"')
            lines.append('')

    return '\n'.join(lines)


def main():
    """Main function to generate pixi.toml."""
    pyproject_data = load_pyproject()
    pixi_content = generate_pixi_toml(pyproject_data)

    # Write to pixi.toml
    output_path = Path(__file__).parent.parent / 'pixi.toml'
    with open(output_path, 'w') as f:
        f.write(pixi_content)

    print(f'Generated {output_path}')


if __name__ == '__main__':
    main()
