name: Set release milestone on PR merge to main
on:
  pull_request_target:
    types: [closed]
    branches:
      - main

permissions: {}

jobs:
  set_milestone:
    runs-on: ubuntu-slim
    if: github.event.pull_request.merged == true &&  github.repository == 'napari/napari'
    permissions:
      pull-requests: write
      issues: write
      contents: read
    steps:
      - name: Ensure closest milestone exists
        id: closest_milestone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IFS='/' read -r repoOwner repoName <<< "${{ github.repository }}"
          TODAY="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          export TODAY

          # shellcheck disable=SC2016
          CLOSEST_MILESTONE_NUMBER=$(gh api graphql -f query='
            query($repoName: String!, $repoOwner: String!) {
              repository(name: $repoName, owner: $repoOwner) {
                milestones(states: OPEN, orderBy: {field: DUE_DATE, direction: ASC}, first: 100) {
                  nodes {
                    title
                    number
                    dueOn
                  }
                }
              }
          }' --jq '.data.repository.milestones.nodes | map(select(.dueOn >= env.TODAY)) | .[0].number' -f repoName="$repoName" -f repoOwner="$repoOwner")

          if [ -z "$CLOSEST_MILESTONE_NUMBER" ]; then
            echo "No open milestone with a future due date was found. Create a new milestone with a future due date."
            echo "CLOSEST_MILESTONE_NAME=" >> "$GITHUB_ENV"
            exit 0
          fi

          # print the closest milestone
          CLOSEST_MILESTONE_NAME=$(gh api "/repos/${{ github.repository }}/milestones/$CLOSEST_MILESTONE_NUMBER" --jq '.title')
          echo "Milestone to apply to PR: $CLOSEST_MILESTONE_NAME"

          echo "name=$CLOSEST_MILESTONE_NAME" >> "$GITHUB_OUTPUT"

      - name: Set milestone on PR
        if: github.event.pull_request.milestone == null && steps.closest_milestone.outputs.name != ''
        run: |
          gh pr edit "$PR_NUMBER" --milestone "$CLOSEST_MILESTONE_NAME"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLOSEST_MILESTONE_NAME: ${{ steps.closest_milestone.outputs.name }}
