name: Build Docs

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true


jobs:
  determine-branch-and-directory-name:
    name: Determine branch and directory name
    runs-on: ubuntu-slim
    outputs:
      target_directory: ${{ steps.get-directory-name.outputs.target_directory }}
      repo_reference: ${{ steps.get-directory-name.outputs.branch_name }}
    steps:
      - name: get directory name from tag
        if: startsWith(github.ref, 'refs/tags/v')
        # if this is a tag, use the tag name as the directory name else dev
        env:
          REF: ${{ github.ref }}
        run: |
          TAG="${GITHUB_REF/refs\/tags\/v/}"
          VER="${TAG/a*/}"  # remove alpha identifier
          VER="${VER/b*/}"  # remove beta identifier
          VER="${VER/rc*/}"  # remove rc identifier
          VER="${VER/post*/}"  # remove post identifier

          echo "target_directory=$VER" >> "$GITHUB_OUTPUT"
          echo "branch_name=$REF" >> "$GITHUB_OUTPUT"

      - name: get directory name from dev deply
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: |
          echo "target_directory=dev" >> "GITHUB_OUTPUT"
          echo "branch_name=main" >> "GITHUB_OUTPUT"

  build-and-deploy:
    uses: napari/shared-workflows/.github/workflows/build_and_deploy.yml@main
    name: Build and deploy
    needs: determine-branch-and-directory-name
    secrets: inherit
    with:
      target_directory: ${{ needs.determine-branch-and-directory-name.outputs.target_directory }}
      napari_ref: ${{ needs.determine-branch-and-directory-name.outputs.repo_reference }}
      docs_ref: main
