name: Build Docs

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  determine-branch-and-directory-name:
    name: Determine branch and directory name
    runs-on: ubuntu-slim
    outputs:
      target_directory: ${{ steps.get-directory-name.outputs.target_directory }}
      repo_reference: ${{ steps.get-directory-name.outputs.branch_name }}
    steps:
      - name: get directory name from tag
        # if this is a tag, use the tag name as the directory name else dev
        id: get-directory-name
        env:
          REF: ${{ github.ref }}
        run: |
          TAG="${GITHUB_REF/refs\/tags\/v/}"
          VER="${TAG/a*/}"  # remove alpha identifier
          VER="${VER/b*/}"  # remove beta identifier
          VER="${VER/rc*/}"  # remove rc identifier
          VER="${VER/post*/}"  # remove post identifier

          if [[ "$REF" == "refs/tags/v"* ]]; then
            echo "branch_name=$REF" >> "$GITHUB_OUTPUT"
            echo "target_directory=$VER" >> "$GITHUB_OUTPUT"
          else
            echo "branch_name=main" >> "$GITHUB_OUTPUT"
            echo "target_directory=dev" >> "$GITHUB_OUTPUT"
          fi

  build-and-deploy:
    uses: napari/shared-workflows/.github/workflows/build_and_deploy.yml@main
    name: Build and deploy
    needs: determine-branch-and-directory-name
    secrets:
      ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
      GOOGLE_CALENDAR_API_KEY: ${{ secrets.GOOGLE_CALENDAR_API_KEY }}
    with:
      target_directory: ${{ needs.determine-branch-and-directory-name.outputs.target_directory }}
      napari_ref: ${{ needs.determine-branch-and-directory-name.outputs.repo_reference }}
      docs_ref: main
