# Full test suite for pull requests - runs only if initial tests pass
name: Full Tests

on:
  workflow_run:
    workflows: ["Initial Tests"]
    types:
      - completed
    branches:
      - main
      - "v*x"

concurrency:
  group: full-test-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

env:
  COLUMNS: 120

jobs:
  check_initial:
    name: Check initial tests passed
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Initial tests passed
        run: echo "Initial tests passed, proceeding with full test suite"

  test:
    name: ${{ matrix.platform }}
    uses: ./.github/workflows/reusable_run_tox_test.yml
    needs: check_initial
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-latest ]
        python: [ "3.11" ]
        backend: [ "pyqt5,pyside6" ]
        coverage: [ cov ]
        include:
          # Windows py310
          - python: "3.11"
            platform: windows-latest
            backend: pyqt5 #,pyside2
            coverage: no_cov
          - python: "3.13"
            platform: windows-latest
            backend: pyqt6
            coverage: cov
          - python: "3.13"
            platform: macos-13
            backend: pyqt5
            coverage: no_cov
          - python: "3.13"
            platform: macos-latest
            backend: pyqt5
            coverage: no_cov
          # minimum specified requirements
          - python: "3.10"
            platform: ubuntu-22.04
            backend: pyqt5
            MIN_REQ: 1
            coverage: cov
          - python: "3.12"
            platform: ubuntu-22.04
            backend: pyqt5
            coverage: cov
            tox_extras: "all_optional"
          # test without any Qt backends
          - python: "3.11"
            platform: ubuntu-22.04
            backend: headless
            coverage: no_cov
          - python: "3.13"
            platform: ubuntu-latest
            backend: pyqt6
            coverage: cov
            tox_extras: "testing_extra"
          # test with no numba
          - python: "3.13"
            platform: ubuntu-latest
            backend: pyqt6_no_numba
            coverage: cov
          # pyside2 test
          - python: "3.10"
            platform: ubuntu-latest
            backend: pyside2
            coverage: no_cov
    with:
      python_version: ${{ matrix.python }}
      platform: ${{ matrix.platform }}
      qt_backend: ${{ matrix.backend }}
      min_req: ${{ matrix.MIN_REQ }}
      coverage: ${{ matrix.coverage }}
      tox_extras: ${{ matrix.tox_extras }}

  test_pip_install:
    needs: check_initial
    name: pip install
    uses: ./.github/workflows/reusable_pip_test.yml

  test_examples:
    name: test examples
    uses: ./.github/workflows/reusable_run_tox_test.yml
    needs: check_initial
    with:
        toxenv: py312-linux-pyqt6-examples-cov
        timeout: 60
        python_version: 3.12
        constraints_suffix: _examples
        coverage: cov

  coverage_report:
    if: ${{ always() }}
    needs:
      - test
      - test_examples
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read    # Required for code checkout
    uses: ./.github/workflows/reusable_coverage_upload.yml
    secrets: inherit
