# https://github.com/marketplace/actions/pr-dependency-check
name: "PR Dependency Check"
on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
  issue_comment:
    types: [ created ]

jobs:
  check_dependencies:
    runs-on: ubuntu-slim
    if: (github.event.issue.pull_request != '' && contains(github.event.comment.body, 'merge')) || github.event_name == 'pull_request'
    name: Check Dependencies
    steps:
    - uses: gregsdennis/dependencies-action@1ba6872857f9adb872a430d5beb027fe10344086 # v1.4.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
