name: Test using dependencies from conda via pixi
on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      platform:
        required: false
        type: string
        default: "ubuntu-latest"
      qt_backend:
        required: false
        type: string
        default: "headless"
      timeout:
        required: false
        type: number
        default: 40

permissions: {}

jobs:
  test:
    runs-on: ${{ inputs.platform }}
    steps:
      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@7d84ae825e6d9297a8e99bdbbae20d1b919a0b19 # v4.2
        with:
          qt: true
          wm: herbstluftwm
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          run-install: false

      - name: Generate pixi.toml
        run: python tools/generate_pixi_toml.py

      - name: Install dependencies
        run: |
          pixi install -e py${PYTHON_VERSION}-${QT_BACKEND}
          pixi list -e py${PYTHON_VERSION}-${QT_BACKEND}
        env:
          PYTHON_VERSION: ${{ inputs.python_version }}
          QT_BACKEND: ${{ inputs.qt_backend }}

      - name: Run tests
        timeout-minutes: ${{ inputs.timeout }}
        run: pixi run -e py${PYTHON_VERSION}-${QT_BACKEND} test
        env:
          PYTHON_VERSION: ${{ inputs.python_version }}
          QT_BACKEND: ${{ inputs.qt_backend }}
