name: Comprehensive Tests

on: [push, pull_request]
# TODO: enable ⏬ and disable ⏫ before merge
# on:
#   push:
#     branches:
#       - master
#     tags:
#       - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  qa:
    name: Code Quality
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [flake8, black, isort]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install tox
      - name: Run task
        run: tox -e ${{ matrix.task }}

  manifest:
    name: Check Manifest
    needs: qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install check-manifest
      - name: Check Manifest
        run: check-manifest

  test:
    needs: qa
    name: ${{ matrix.platform }} py${{ matrix.python }} ${{ matrix.toxenv }} ${{ matrix.MIN_REQ && '(minreq)' }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.7, 3.8, 3.9]
        include:
          # test big sur on 3.9.0
          - python: 3.9
            platform: macos-11.0
            toxenv: py390-macos-pyqt
          # test with minimum specified requirements
          - python: 3.7
            platform: ubuntu-18.04
            MIN_REQ: 1
          # test with --async_only
          - python: 3.8
            platform: ubuntu-18.04
            toxenv: async-py38-linux-pyqt
          # test with --perfmon-only
          - python: 3.8
            platform: ubuntu-18.04
            toxenv: perfmon-py38-linux-pyqt

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Setup Miniconda
        if: runner.os == 'macOS' && matrix.python == '3.9'
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          channels: conda-forge
          channel-priority: strict
          python-version: ${{ matrix.python }}

      - name: Install Linux libraries
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 \
            libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 \
            libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0

      - name: Install Windows OpenGL
        if: runner.os == 'Windows'
        run: |
          git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git
          powershell gl-ci-helpers/appveyor/install_opengl.ps1

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools tox tox-gh-actions
          python tools/minreq.py  # no-op if MIN_REQ is not set
        env:
          MIN_REQ: ${{ matrix.MIN_REQ }}

      - name: Install tox-conda
        if: runner.os == 'macOS' && matrix.python == '3.9'
        run: pip install tox-conda>=0.5.0

      - name: Test with tox
        shell: bash -l {0}
        run: tox
        env:
          PLATFORM: ${{ matrix.platform }}
          TOXENV: ${{ matrix.toxenv }}
          NUMPY_EXPERIMENTAL_ARRAY_FUNCTION: ${{ matrix.MIN_REQ || 1 }}
          PYVISTA_OFF_SCREEN: True

      - name: Coverage
        if: runner.os == 'Linux' && matrix.python == '3.9'
        uses: codecov/codecov-action@v1

      - name: Report Failures
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PLATFORM: ${{ matrix.platform }}
          PYTHON: ${{ matrix.python }}
          BACKEND: ${{ matrix.toxenv }}
          RUN_ID: ${{ github.run_id }}
          TITLE: '[test-bot] Comprehensive tests failing'
        with:
          filename: .github/TEST_FAIL_TEMPLATE.md
          update_existing: true