name: Type-check

on:
  pull_request:
    branches:
      - main

concurrency:
  group: typing-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.12"
          cache-dependency-path: pyproject.toml
      - name: Install tox
        run: |
          pip install tox

      - name: Run mypy on typed modules
        run: tox -e mypy
